---
development: &defaults
  adapter: couchdb
  database: lifestyle-development
  host: localhost
  port: 5984

test:
  <<: *defaults
  database: lifestyle-test

production:
  <<: *defaults
  database: lifestyle-production

rake:
  <<: *defaults
