--- !ditz.rubyforge.org,2008-03-06/project 
name: lifestyle
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: lifestyle
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.1
  status: :released
  release_time: 2008-12-24 00:16:36.399094 Z
  log_events: 
  - - 2008-12-06 20:01:45.175245 Z
    - Michael Zink <zuwiki@gmail.com>
    - created
    - Just the models.
  - - 2008-12-24 00:16:36.399104 Z
    - Michael Zink <zuwiki@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.2
  status: :released
  release_time: 2008-12-26 20:47:03.907749 Z
  log_events: 
  - - 2008-12-06 20:02:16.839208 Z
    - Michael Zink <zuwiki@gmail.com>
    - created
    - Now with controllers and super-barebones views.
  - - 2008-12-26 20:47:03.907764 Z
    - Michael Zink <zuwiki@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.3
  status: :released
  release_time: 2009-01-10 18:43:43.707213 Z
  log_events: 
  - - 2008-12-24 17:59:37.194391 Z
    - Michael Zink <zuwiki@gmail.com>
    - created
    - ""
  - - 2009-01-10 18:43:43.707228 Z
    - Michael Zink <zuwiki@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.4
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-01-10 18:45:11.554797 Z
    - Michael Zink <zuwiki@gmail.com>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.5
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-01-14 10:50:25.700081 Z
    - Michael Zink <zuwiki@gmail.com>
    - created
    - ""
