--- !ditz.rubyforge.org,2008-03-06/project 
name: lifestyle
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: lifestyle
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.1
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-12-06 20:01:45.175245 Z
    - Michael Zink <zuwiki@gmail.com>
    - created
    - Just the models.
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.0.2
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-12-06 20:02:16.839208 Z
    - Michael Zink <zuwiki@gmail.com>
    - created
    - Now with controllers and super-barebones views.
